// auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHECKING_USER_LOGIN = 'CHECKING_USER_LOGIN';
export const NO_USER_LOGGED_IN = 'NO_USER_LOGGED_IN';

//fridge
export const PURCHASES_FETCH_SUCCESS = 'PURCHASES_FETCH_SUCCESS';
export const PURCHASES_FETCHING = 'PURCHASES_FETCHING';
export const PURCHASES_FETCH_NO_RESULTS = 'PURCHASE_FETCH_NO_RESULTS';

// purchase
export const PURCHASE_UPDATE = 'PURCHASE_UPDATE';
export const PURCHASE_SAVING = 'PURCHASE_SAVING';
export const PURCHASE_SAVE_SUCCESS = 'PURCHASE_SAVE_SUCCESS';
export const PURCHASE_FETCHING = "PURCHASE_FETCHING";
export const PURCHASE_FETCH_SUCCESS = "PURCHASE_FETCH_SUCCESS";
export const PURCHASE_DELETING = 'PURCHASE_DELETING';
export const PURCHASE_DELETE_SUCCESS = 'PURCHASE_DELETE_SUCCESS';

// product
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_SAVING = 'PRODUCT_SAVING';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_FETCHING = 'PRODUCT_FETCHING';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_SEARCHING = 'PRODUCT_SEARCHING';
export const PRODUCT_SEARCH_NO_RESULTS = 'PRODUCT_SEARCH_NO_RESULTS';
export const PRODUCT_SEARCH_GOT_RESULT = 'PRODUCT_SEARCH_GOT_RESULT';

// report
export const REPORT_UPDATE = 'REPORT_UPDATE';
export const REPORT_SAVING = 'REPORT_SAVING';
export const REPORT_SAVE_SUCCESS = 'REPORT_SAVE_SUCCESS';


export const RESET = 'RESET';
